insert into student  values(1,'java','aa@aa','aaa')
insert into student  values(2,'c#','bb@bb','bbb')
insert into student  values(3,'java','ccc@ccc','ccc')
insert into student  values(4,'python','dd@dd','ddd')
insert into student  values(5,'php','ee@ee','eee')